version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: trafilea-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trafilea-container
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://trafilea-mongo-container:27017/
      - MONGO_DB_NAME=trafilea
      - PORT=4000

volumes:
  mongo-data:
